### ISSUE TITLE
Warning: forceUpdate(...): Can only update a mounted or mounting component...

### ISSUE THREAD

**Issue by ykshev** [ultimatejs/tracker-react#11]
Thanks for your work. I decided to test it out and when I'm switching to a next page, I get in console this warning:

``` javascript
Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the undefined component.
```

React component is pretty standart

``` javascript
export default class ProjectsContainer extends TrackerReact(React.Component)  {
    constructor(props) {
        super(props);
        this.state = {
            error: '',
            subscription: {
                projects: Meteor.subscribe( 'Projects.Private' )
            }
        };
    }
    componentWillUnmount() {
        this.state.subscription.projects.stop();
    }
    projects() {
        return Projects.find({}, {sort: {createdAt: -1}}).fetch();
    }
    render() {
        //Mapping cards
        const cardsList = this.projects().map((project) => {
                return <ProjectCard project={project} key={project._id}/>;
        });
        return <div className="row projects-container">
            {this.state.subscription.projects.ready() ? cardsList : 'Loading...'}
        </div>
    }
}
```

if I comment out this part

``` javascript
    componentWillUnmount() {
        this.state.subscription.projects.stop();
    }
```

the warning disappears. As a router I'm using "Flow-router". Meteor 1.3beta12. Any ideas how to fix it?

**Comment by D1no** [comment]
Ok, I reproduced it with React 14.7 - I will update and re-publish TrackerReact later tonight.

It has something todo with the fact that we force an update on data invalidation, which a stop of subscriptions are, but at this time the component is not there anymore. The react team increased the speed of react again by 10% - presumably by making the unmount asynchronous, letting us fire into the dark.... and now warning about it.

For now, ignore the warning or stop the computation before stopping the subscription like so:

``` jsx
componentWillUnmount() {
        this._renderComputation.stop();
        this.state.subscription.projects.stop();
    }
```

**Comment by ykshev** [comment]
Thanks for the fast fix. But after I updated to 1.0.1 I've got this error and the whole app fell down:

```
Uncaught TypeError: Cannot read property 'profiler' of undefined profiler.js:11

TrackerReactLog @   profiler.js:11
TrackerReactComponent   @   main.js:38
ProjectsContainer   @   projectsContainer.jsx:14
ReactCompositeComponentMixin.mountComponent @   ReactCompositeComponent.js:148
..... 
```

http://take.ms/5fHYB

as you could see this refer to 14 line of my component above and it is `super(props);`. If I roll back to 1.0.0 version it works fine, but with warning.

**Comment by D1no** [comment]
@tastemeru Please try version 1.0.2 - it was updated. The current profiler implementation is not the best, because meteor handles commonJS requires different than node; so the profiler import is not available in a constructor call. This should work now - a todo for the future.

**Comment by ykshev** [comment]
I've tried to remove and then install the plugin again and it seems as last version `ultimatejs:tracker-react@1.0.2` , but the error still there. May be I can provide more info about the bug some way?

**Comment by D1no** [comment]
It would help if you could provide a repo reproduction. I am a little tight
in time right now.
